./sub.pl articles.template.html sidebar.html
./sub.pl videocourses.template.html sidebar.html
./sub.pl career_options.template.html sidebar.html
./sub.pl contact.template.html sidebar.html
./sub.pl contact.template.html research_sidebar.html 7 contact_research.html
./sub.pl expectations.template.html sidebar.html
./sub.pl model.template.html sidebar.html
./sub.pl phd_investment.template.html sidebar.html
./sub.pl phdhowto.template.html sidebar.html
./sub.pl phd_true_meaning.template.html sidebar.html 
./sub.pl publications.template.html research_sidebar.html
./sub.pl patents.template.html research_sidebar.html
./sub.pl openings.template.html research_sidebar.html
./sub.pl projects.template.html research_sidebar.html
./sub.pl research.template.html research_sidebar.html
./sub.pl index.template.html sidebar.html
./sub.pl teaching.template.html sidebar.html
./sub.pl workshops.template.html sidebar.html
./sub.pl why_do_phd.template.html sidebar.html
./sub.pl summer_students.template.html sidebar.html
./sub.pl software.template.html research_sidebar.html
./sub.pl masters.template.html sidebar.html
./sub.pl phdfaqs.template.html sidebar.html
./sub.pl startups.template.html sidebar.html
./sub.pl jee.template.html sidebar.html
./sub.pl sric.template.html sidebar.html
./sub.pl short_term_course.template.html sidebar.html
./sub.pl members.template.html research_sidebar.html
./sub.pl jitter.template.html research_sidebar.html
./sub.pl phd_india_us.template.html sidebar.html
./sub.pl archbooksoft.template.html sidebar.html
./sub.pl buyitlink.template.html sidebar.html
./sub.pl media.template.html sidebar.html
